###############################################################################
#### Properties for local development along with CF environment
###############################################################################
identity:
  protocol: DCCVALIDATION
  protocolVersion: 1.0.0
  #### serviceIdentity
  serviceIdentityUrl: https://validation-decorator.example
  privacyUrl: https://privacyUrl.example.com
  consent: I want to check your DCC to confirm your booking! :)
  serviceProvider: Service Provider.com
  restTemplate:
    connectionTimeout: 3000
    readTimeout: 3000

booking:
  urls:
    tokenContent: https://dgca-booking-demo-backend-eu-test.cfapps.eu10.hana.ondemand.com/tokencontent/{subject}
    result: https://dgca-booking-demo-backend-eu-test.cfapps.eu10.hana.ondemand.com/result/{subject}

#### Create Key: keytool -genkey -alias [ALIAS NAME] -keyalg EC -validity 3650 -keystore dev-decorator.jks -storetype JKS
dgc:
  #### Validation Decorator URI without trailing slash
  serviceUrl: http://localhost:8080
  keyStoreFile: certs/dev-decorator.jks
  keyStorePassword: changeMe
  privateKeyPassword: changeMe
  #### activeSignKey must be one of signAliases
  activeSignKey: AccessTokenSignKey-1
  encAliases:
  signAliases:
    - AccessTokenSignKey-1
  keyAliases:
    - AccessTokenServiceKey-1
    - ServiceProviderKey-1
    - CancellationServiceKey-1
    - StatusServiceKey-1
    - ValidationServiceKey-1
  token:
    issuer: Validation Decorator Service
    type: JWT
    initialize:
      #### in seconds. Expiration is calculated
      validity: 3600
  #### Validation Service
  services:
    - id: ${dgc.serviceUrl}/identity/service/ValidationService#ValidationService-1
      type: ValidationService
      serviceEndpoint: https://dgca-validation-service-eu-test.cfapps.eu10.hana.ondemand.com
      name: Validation Service
  #### Validation Decorator
  endpoints:
    - id: ${dgc.serviceUrl}/identity/service/AccessTokenService#AccessTokenService-1
      type: AccessTokenService
      serviceEndpoint: ${dgc.serviceUrl}/token
      name: Validation Decorator Token
    - id: ${dgc.serviceUrl}/identity/service/ServiceProvider#ServiceProvider-1
      type: ServiceProvider
      serviceEndpoint: ${dgc.serviceUrl}/identity
      name: Validation Decorator Identity
    - id: ${dgc.serviceUrl}/identity/service/CancellationService#CancellationService-1
      type: CancellationService
      serviceEndpoint: ${dgc.serviceUrl}/reject
      name: Validation Decorator Reject
    - id: ${dgc.serviceUrl}/identity/service/StatusService#StatusService-1
      type: StatusService
      serviceEndpoint: ${dgc.serviceUrl}/status
      name: Validation Decorator Status

server:
  port: 8080

spring:
  application:
    name: dgca-validation-decorator

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health

springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger
